universe = vanilla
container_image = osdf:///ospool/uc-shared/public/OSG-Staff/xalim_stat/R_tidyverse_FITSio.sif
executable = process_chunk.sh
arguments = $(PART)
output = output/$(PART).out
error = error/$(PART).err
log = logs/$(PART).log
request_cpus = 1
request_memory = 6GB
request_disk = 5GB
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = process_chunk.R, $(PART)
queue PART from parts.list

